services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - ./symfony/:/var/www/html
    environment:
      - APP_ENV=dev
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./symfony/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf